blocks/accordion-dropdown/accordion-dropdown.js, blocks/accordion-dropdown/accordion-new.css, blocks/accordion-dropdown/disclaimer-footer.css, blocks/accordion-dropdown/quick-links-footer.css, blocks/accordion-group/accordion-group.js, blocks/accordion-group/accordion-new.css, blocks/accordion-group/disclaimer-footer.css, blocks/accordion-group/quick-links-footer.css, blocks/carousel/custom-carousel.css, blocks/carousel/life-insurance.css, blocks/carousel/reviews.css, blocks/columns/insurance-app.css, blocks/columns/trusted-companies.css, blocks/custom-card/insurance-plans-cards/insurance-plans-cards.css, blocks/custom-card/prefer-max-life-cards/prefer-max-life-cards.css, blocks/custom-card/term-insurance-cards/term-insurance-cards.css, blocks/header/custom-header.css, blocks/modal/modal.js, blocks/popular-searches/popular-searches.css, blocks/teaser/claims-paid-percentage.css, scripts/delayed.js
Test URLs:
- After: https://gtm-script-impl--internal-eds-poc-en--tekno-point.hlx.live/max-life/
=> gtm script loaded in head

blocks/header/desk-nav-modal.css, blocks/header/header.js
Test URLs:
- After: https://form-impl--internal-eds-poc-en--tekno-point.hlx.live/max-life/
=> CSS update

component-models.json, styles/styles.css
Test URLs:
- After: https://issue-cards--internal-eds-poc-en--tekno-point.hlx.live/max-life/
=> class added to section

styles/styles.css
Test URLs:
- After: https://issue-cards--internal-eds-poc-en--tekno-point.hlx.live/max-life/
=> padding class added to section

blocks/wrappercreation/wrappercreation.css
Test URLs:
- After: https://issue-cards--internal-eds-poc-en--tekno-point.hlx.live/max-life/
=> custom card js file created and wrappercreation css file created

component-models.json
=>  component model class added

blocks/carousel/banner-carousel.css, blocks/teaser/life-stage-wrapper.css
=>  banner css added

blocks/header/header.css, blocks/header/header.js, styles/reset.css
Test URLs:
Before: https://nippon--internal-eds-poc-en--tekno-point.hlx.live/
After: https://feature-nippon-model--internal-eds-poc-en--tekno-point.hlx.live/
=>  mobile header in progrss

component-models.json, styles/styles.css
=>  add margin class iin common

blocks/accordion-dropdown/accordion-dropdown.css, blocks/accordion-dropdown/important-links.css, blocks/teaser/life-stage-wrapper.css
=>  footer css added

blocks/quicklinks/quicklinks.css, blocks/videoteaser/videoteaser.css, blocks/videoteaser/videoteaser.js, component-definition.json, component-filters.json, component-models.json
=>  component creation

styles/styles.css
=>  add common css

component-models.json
=>  add class in modles for section

blocks/accordion-dropdown/accordion-dropdown.css, blocks/accordion-dropdown/important-links.css, blocks/accordion-dropdown/product-accordian.css
=> Block modal

blocks/accordion-dropdown/product-accordian.css, blocks/carousel/banner-carousel.css, blocks/carousel/carousel-config.js, blocks/header/header.js, blocks/videoteaser/videoteaser.css
Test URLs:
- Before: https://nippon--internal-eds-poc-en--Tekno-Point.hlx.live/nippon/
- After: https://block-modal--internal-eds-poc-en--Tekno-Point.hlx.live/nippon/
=>  es-lint fixes done

blocks/header/header.css
Test URLs:
- Before: https://nippon--internal-eds-poc-en--Tekno-Point.hlx.live/nippon/
- After: https://feature-nippon-sites--internal-eds-poc-en--Tekno-Point.hlx.live/nippon/
=>  header css done

blocks/header/header.css, blocks/header/header.js
Test URLs:
- Before: https://nippon--internal-eds-poc-en--tekno-point.hlx.live/nippon/
- After: https://block-modal--internal-eds-poc-en--tekno-point.hlx.live/nippon/
=>  dropdown js added

blocks/newcarousel/newcarousel.css, blocks/newcarousel/newcarousel.js, component-definition.json, component-filters.json, component-models.json
=>  new carousel component created

component-models.json
=> classes added to section and carousel

component-definition.json, component-filters.json, component-models.json
Test URLs:
- Before: https://main--internal-eds-poc-en--Tekno-Point.hlx.live/hdfclife/
- After: https://block-impl--internal-eds-poc-en--Tekno-Point.hlx.live/hdfclife/
=> xf block created

component-definition.json, component-filters.json, component-models.json
=> new container created

blocks/rte/code.js, blocks/rte/table.js, component-definition.json, component-filters.json, component-models.json
=> add tables blocks code

component-models.json
=> add one class and modify class name eds-container-width to eds-container

component-models.json
=> Block impl

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://<branch>--internal-eds-poc-en--Tekno-Point.hlx.live/
=>  bandhan bank header first push

component-models.json
=> add class in bandhan-bank-carousel

paths.json
=> form added for bandhan bank

component-models.json
=> saving acc style added

component-models.json
=> add one class

component-models.json
=> container new image-only-container class

component-definition.json, component-filters.json, component-models.json
=> code block added
